name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs: # JSON Schema sepc: https://json-schema.org/
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'